from . import replay_tab
from . import missing_tab
from . import error_tab
from . import step_tab
from . import manual_tab
from . import binary_tab
from . import wizard_tab
from . import sniffer_tab
from . import chart_tab
from . import ml_analysis_tab
from . import pattern_tab
from . import server_tab
from . import generator_tab
from . import macro_tab
from . import advanced_ml_tab
